
mainpage:
    path:     /
    defaults: { _controller: 'AppBundle\Controller\CatalogController::indexAction' }
contacts:
    path:     /contacts
    defaults: { _controller: 'AppBundle\Controller\ContactsController::indexAction' }
product:
    path:     /{slug}.html
    defaults: { _controller: 'AppBundle\Controller\CatalogController::productAction' }
category:
    path:     /{slug}
    defaults: { _controller: 'AppBundle\Controller\CatalogController::categoryAction' }